library(lubridate)
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", destfile = "./data.zip", method = "curl")
unzip("data.zip")
housedata <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
housedata$Date <- dmy(housedata$Date)
selectdata <- housedata[housedata$Date == "2007-02-01" | housedata$Date == "2007-02-02", ]
globalactivepower <- as.numeric(selectdata$Global_active_power)
png("plot1.png", width = 480, height = 480)
par(mar = c(5,5,3,2))
hist(globalactivepower, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency", xaxt = "n")
axis(1, at = c(0,1000,2000,3000), labels = c("0", "2", "4", "6"))
dev.off()